//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFFILIATEPAYMENT
    {
        public decimal ID { get; set; }
        public decimal PROGRAM { get; set; }
        public decimal AMOUNT { get; set; }
        public System.DateTime THEDATE { get; set; }
        public string NOTES { get; set; }
    }
}
