//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFFILIATECOMMISSION
    {
        public decimal ID { get; set; }
        public decimal PROGRAM { get; set; }
        public decimal ORDERID { get; set; }
        public decimal AMOUNT { get; set; }
    }
}
