//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFFILIATEPROGRAM
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public decimal COMMISSIONSCALAR { get; set; }
        public bool COMMISSIONTYPE { get; set; }
        public decimal DISCOUNTSCALAR { get; set; }
        public bool DISCOUNTTYPE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string COMPANYNAME { get; set; }
        public string CONTACTEMAIL { get; set; }
        public string WEBSITEURL { get; set; }
        public string PAYPALACCOUNTEMAIL { get; set; }
    }
}
