//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        public decimal ID { get; set; }
        public string TITLE { get; set; }
        public string TEXT { get; set; }
        public Nullable<System.DateTime> POSTDATE { get; set; }
        public string SUBTITLE { get; set; }
        public string STATES { get; set; }
        public Nullable<bool> FEATURED { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string PREVIEW { get; set; }
        public Nullable<int> CATEGORY2 { get; set; }
        public string AUTHORS { get; set; }
        public string KEYWORDS { get; set; }
        public Nullable<bool> STATELAWSUMMARY { get; set; }
        public Nullable<bool> HASBANNER { get; set; }
        public string BANNERCAPTION { get; set; }
        public Nullable<bool> POSTED { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public string BANNERFILENAMEBASE { get; set; }
        public string THUMBNAILFILENAMEBASE { get; set; }
        public bool HASRETINATHUMBNAILS { get; set; }
    }
}
