//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSOCIATION
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string WEBURL { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string PHONE { get; set; }
        public string ALTPHONE { get; set; }
        public string CONTACT { get; set; }
        public string MEMBERSHIPDUES { get; set; }
        public string MEETINGTIME { get; set; }
        public string MEETINGLOCATION { get; set; }
        public Nullable<decimal> NUMOFMEMBERS { get; set; }
        public string PHILOSOPHY { get; set; }
        public string NOTES { get; set; }
        public string EMAIL { get; set; }
        public string AREASERVED { get; set; }
        public string ASSOCIATIONADDRESS { get; set; }
        public string COUNTRY { get; set; }
    }
}
