//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOFILLPROFILE
    {
        public Nullable<decimal> BUILTID { get; set; }
        public decimal USERID { get; set; }
        public string SENDERNAME { get; set; }
        public string SENDERADDRESS1 { get; set; }
        public string SENDERADDRESS2 { get; set; }
        public string SENDERCITY { get; set; }
        public string SENDERSTATE { get; set; }
        public string SENDERZIP { get; set; }
        public string SENDERPHONE { get; set; }
        public string SENDERFAX { get; set; }
        public string SENDEREMAIL { get; set; }
        public string RECIPNAME { get; set; }
        public string RECIPADDRESS1 { get; set; }
        public string RECIPADDRESS2 { get; set; }
        public string RECIPCITY { get; set; }
        public string RECIPSTATE { get; set; }
        public string RECIPZIP { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> LEASEID { get; set; }
        public Nullable<bool> ISCURRENT { get; set; }
        public string SENDERCOUNTRY { get; set; }
        public string RECIPCOUNTRY { get; set; }
    }
}
