//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMDOCUMENT
    {
        public decimal ID { get; set; }
        public string BODYTEXT { get; set; }
        public Nullable<bool> TEMPLATE { get; set; }
        public Nullable<decimal> ORIGINALDOCID { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
    }
}
