//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCBUILDERCHECKIN
    {
        public string ADDRESS { get; set; }
        public Nullable<int> PORT { get; set; }
        public Nullable<System.DateTime> CHECKIN { get; set; }
        public Nullable<bool> TYPE { get; set; }
        public Nullable<System.DateTime> LASTJOB { get; set; }
        public Nullable<byte> PORTRANGE { get; set; }
        public Nullable<int> LASTPORT { get; set; }
        public string SWVERSION { get; set; }
        public Nullable<long> LEASETIMEMS { get; set; }
        public int ID { get; set; }
    }
}
