//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCS2RELATEDARTICLES
    {
        public decimal DOCID { get; set; }
        public decimal ARTICLEID { get; set; }
        public Nullable<byte> POSITION { get; set; }
    }
}
