//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTRATING
    {
        public int ID { get; set; }
        public int USERID { get; set; }
        public byte RATING { get; set; }
        public int DOCUMENTID { get; set; }
    }
}
