//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_PROMPTS
    {
        public decimal DOCUMENT { get; set; }
        public string FIELD { get; set; }
        public string PROMPT { get; set; }
    }
}
