//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT
    {
        public decimal ID { get; set; }
        public Nullable<decimal> CATEGORY { get; set; }
        public string NAME { get; set; }
        public string FILEFORMAT { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public string KEYWORDS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<byte> AVAILABILITY { get; set; }
        public Nullable<bool> PREVIEW { get; set; }
        public Nullable<bool> ICON { get; set; }
        public Nullable<bool> PRINTINGINSTRUCTIONS { get; set; }
        public Nullable<bool> CUSTOMIZABLE { get; set; }
        public Nullable<bool> PROPERTYSELECTONLY { get; set; }
        public string WHENSENT { get; set; }
        public string WHOGETS { get; set; }
        public string LONGDESC { get; set; }
        public Nullable<bool> USECUSTOMLOGO { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<bool> FORALLUSERS { get; set; }
        public Nullable<bool> ISEDITABLE { get; set; }
        public string LONGDESC2 { get; set; }
        public string LONGDESC3 { get; set; }
        public Nullable<byte> SORTORDER { get; set; }
        public string LONGDESC4 { get; set; }
        public string STATES { get; set; }
        public Nullable<bool> ISEMAILABLE { get; set; }
        public Nullable<decimal> CATEGORY2 { get; set; }
        public Nullable<bool> DEFAULTINLEASE { get; set; }
        public Nullable<bool> RESIDENTIALWIZARD { get; set; }
        public Nullable<bool> COMMERCIALWIZARD { get; set; }
        public Nullable<bool> DEFAULTINCOMMERCIALLEASE { get; set; }
        public Nullable<bool> VACATIONWIZARD { get; set; }
        public Nullable<bool> DEFAULTINVACATIONLEASE { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<bool> HASRETINATHUMBNAIL { get; set; }
        public string THUMBNAILFILENAMEBASE { get; set; }
        public Nullable<bool> HASLANDINGPAGEIMAGE { get; set; }
        public string LANDINGPAGEFILENAMEBASE { get; set; }
        public Nullable<bool> HASRETINAPREVIEWS { get; set; }
        public Nullable<byte> PDFTYPE { get; set; }
    }
}
