//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTFEATURE
    {
        public decimal DOCUMENT { get; set; }
        public bool AUTOFILL { get; set; }
        public bool WINDOWENV { get; set; }
        public bool EMAILABLE { get; set; }
        public bool CUSTOMLOGO { get; set; }
        public byte PAGES { get; set; }
    }
}
