//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTEMAIL
    {
        public decimal ID { get; set; }
        public Nullable<decimal> BUILTID { get; set; }
        public Nullable<System.DateTime> DATESENT { get; set; }
        public Nullable<decimal> LEASEID { get; set; }
        public Nullable<decimal> DOCUMENT { get; set; }
        public Nullable<bool> ISREAD { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> READDATE { get; set; }
        public Nullable<bool> EMAILSTATUS { get; set; }
    }
}
