//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESIGN_ACTIVITYLOG
    {
        public decimal ACTIVITYID { get; set; }
        public Nullable<decimal> ACTIVITYTYPEID { get; set; }
        public string COMMENTS { get; set; }
        public decimal ESIGNREQUESTID { get; set; }
        public Nullable<System.DateTime> ACTIVITYDATE { get; set; }
        public Nullable<decimal> LOGGEDUSERID { get; set; }
    }
}
