//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESIGN_REQUEST
    {
        public decimal ESIGNREQUESTID { get; set; }
        public string APIREQUESTID { get; set; }
        public decimal STATUSID { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<System.DateTime> DATEALLSIGNED { get; set; }
        public Nullable<System.DateTime> DATEDOWNLOADED { get; set; }
        public Nullable<decimal> BUILTID { get; set; }
        public Nullable<decimal> LEASEID { get; set; }
        public Nullable<decimal> LANDLORDID { get; set; }
        public Nullable<System.DateTime> DATESENTCALLBACK { get; set; }
    }
}
