//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESIGN_WORKFLOW
    {
        public decimal ESIGNWORKFLOWID { get; set; }
        public decimal ESIGNREQUESTID { get; set; }
        public decimal USERID { get; set; }
        public Nullable<decimal> ESIGNORDER { get; set; }
        public Nullable<decimal> USERTYPE { get; set; }
        public string EMAIL { get; set; }
        public string APISIGNATUREID { get; set; }
        public Nullable<System.DateTime> DATESENT { get; set; }
        public Nullable<System.DateTime> DATEVIEWED { get; set; }
        public Nullable<System.DateTime> DATESIGNED { get; set; }
        public Nullable<System.DateTime> DATEREMINDER { get; set; }
    }
}
