//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVESTMENTPERFORMANCE
    {
        public Nullable<decimal> PROPERTYID { get; set; }
        public Nullable<decimal> CURRENTTOTALVALUE { get; set; }
        public Nullable<decimal> PURCHASEPRICE { get; set; }
        public Nullable<decimal> TOTALCOSTOFREPAIRS { get; set; }
        public Nullable<decimal> REALESTATETAXESYEAR { get; set; }
        public Nullable<decimal> INSURANCEYEAR { get; set; }
        public Nullable<decimal> REPAIRSYEAR { get; set; }
        public Nullable<decimal> WATERBILLMONTH { get; set; }
        public Nullable<decimal> RENTRECEIVEDMONTH { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> DOWNPAYMENT { get; set; }
        public Nullable<decimal> INITIALREPAIRCOST { get; set; }
        public Nullable<decimal> CLOSINGCOSTS { get; set; }
        public Nullable<decimal> VACANCYRATE { get; set; }
        public Nullable<decimal> MANAGEMENTRATE { get; set; }
        public int ID { get; set; }
    }
}
