//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LATEFEE
    {
        public decimal ID { get; set; }
        public decimal LEASE { get; set; }
        public Nullable<byte> DAYS { get; set; }
        public Nullable<decimal> AMOUNTSCALAR { get; set; }
        public Nullable<byte> AMOUNTTYPE { get; set; }
        public Nullable<bool> EMAIL { get; set; }
    }
}
