//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEASESTOBUILD
    {
        public decimal ID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public decimal LEASE { get; set; }
        public Nullable<byte> PERCENT { get; set; }
        public Nullable<System.DateTime> TIMEINSERTED { get; set; }
        public Nullable<System.DateTime> CHECKIN { get; set; }
        public Nullable<bool> ISTRIAL { get; set; }
        public string EMAILMESSAGE { get; set; }
        public string BUILDER { get; set; }
        public Nullable<bool> ISTRIALREBUILD { get; set; }
        public Nullable<bool> USEDEVBUILDER { get; set; }
    }
}
