//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEASEOPTIONSBYSTATE
    {
        public string STATE { get; set; }
        public Nullable<bool> PETDEPOSITOPTION { get; set; }
        public Nullable<bool> COURTCOSTSOPTION { get; set; }
        public Nullable<bool> HOLDOVEROPTION { get; set; }
        public Nullable<bool> ATTORNEYFEESOPTION { get; set; }
        public Nullable<bool> ACCELERATIONCLAUSE { get; set; }
        public Nullable<byte> RIGHTOFENTRYNOTICEHOURS { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<bool> WAIVETENANTNOTICERIGHT { get; set; }
    }
}
