//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINK
    {
        public decimal ID { get; set; }
        public Nullable<decimal> CATEGORYID { get; set; }
        public string NAME { get; set; }
        public string WEBURL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> NOFOLLOW { get; set; }
        public string DISPLAYURL { get; set; }
        public bool USEHTTPS { get; set; }
    }
}
