//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LT_STATEPROV
    {
        public int STATEPROV_ID { get; set; }
        public int COUNTRY_ID { get; set; }
        public string STATE_ABBREVIATION { get; set; }
        public string STATEPROV_DESC { get; set; }
    }
}
