//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAILINGLIST
    {
        public decimal ID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> NEWSLETTER { get; set; }
        public Nullable<bool> REMINDERS { get; set; }
        public Nullable<bool> LAWUPDATE { get; set; }
    }
}
