//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public decimal ID { get; set; }
        public decimal THREAD { get; set; }
        public string SUBJECT { get; set; }
        public string BODY { get; set; }
        public string STATE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> FEATURED { get; set; }
        public Nullable<byte> CATEGORY { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<System.DateTime> MSGDATE { get; set; }
    }
}
