//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLLQUESTION
    {
        public decimal ID { get; set; }
        public Nullable<decimal> POLLID { get; set; }
        public string QUESTION { get; set; }
        public Nullable<byte> SORTORDER { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    }
}
