//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPERTy
    {
        public decimal ID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public Nullable<decimal> BEDS { get; set; }
        public Nullable<decimal> BATHS { get; set; }
        public Nullable<decimal> RESIDENCETYPE { get; set; }
        public string RESIDENCETYPEOTHER { get; set; }
        public Nullable<decimal> SMOKINGALLOWED { get; set; }
        public Nullable<short> HALFBATHS { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<bool> BUILT { get; set; }
        public Nullable<decimal> TRANSUNIONPROPERTYID { get; set; }
        public string MEASUREMENTS { get; set; }
        public string LEGALDESC { get; set; }
        public string FURTHERDESC { get; set; }
        public string COMMUNITYNAME { get; set; }
    }
}
