//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASEOPTIONAGREEMENT
    {
        public decimal LEASE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<byte> DAYSNOTICE { get; set; }
        public Nullable<decimal> CUSTOMID { get; set; }
    }
}
