//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA_FINANCIALINFO
    {
        public decimal ID { get; set; }
        public Nullable<decimal> APPLICANTID { get; set; }
        public Nullable<byte> TYPE { get; set; }
        public string COMPANY { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<decimal> MONTHLYPAYMENT { get; set; }
        public string CREDITORSPHONE { get; set; }
        public string ACCOUNTNUMBER { get; set; }
    }
}
