//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA_PET
    {
        public decimal ID { get; set; }
        public Nullable<decimal> APPLICANTID { get; set; }
        public string NAME { get; set; }
        public string TYPEBREED { get; set; }
        public Nullable<byte> ISINDOORPET { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public Nullable<decimal> SORTORDER { get; set; }
    }
}
