//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RA_VEHICLE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> APPLICANTID { get; set; }
        public Nullable<decimal> YEAR { get; set; }
        public string MAKE { get; set; }
        public string MODEL { get; set; }
        public string COLOR { get; set; }
        public string PLATENUMBER { get; set; }
        public Nullable<byte> ISFINANCED { get; set; }
        public Nullable<decimal> FINANCING { get; set; }
        public Nullable<decimal> SORTORDER { get; set; }
    }
}
