//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCE
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string WEBURL { get; set; }
        public string DESCRIPTION { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public Nullable<bool> RESOURCETYPE { get; set; }
        public string PHONE { get; set; }
        public string PRACTICEYEAR { get; set; }
        public string GENERALPHILOSOPHY { get; set; }
        public string PRIMARYPRACTICE { get; set; }
        public string SUBCATEGORIES { get; set; }
        public string BAMC { get; set; }
        public string SCHOOL1 { get; set; }
        public string DEGREE1 { get; set; }
        public string SCHOOLYEARS1 { get; set; }
        public string HONORS1 { get; set; }
        public string FA1 { get; set; }
        public string SCHOOL2 { get; set; }
        public string DEGREE2 { get; set; }
        public string SCHOOLYEARS2 { get; set; }
        public string HONORS2 { get; set; }
        public string FA2 { get; set; }
        public string FEES { get; set; }
        public string RATES { get; set; }
        public string FREECONSULTATION { get; set; }
        public string RETAINER { get; set; }
        public string FIRMNAME { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string SCHOOL3 { get; set; }
        public string DEGREE3 { get; set; }
        public string SCHOOLYEARS3 { get; set; }
        public string HONORS3 { get; set; }
        public string FA3 { get; set; }
        public string COUNTRY { get; set; }
        public string CONTACTNAME { get; set; }
        public string AREASERVED { get; set; }
        public string ALLOWEDPROPERTYTYPES { get; set; }
        public string MAXLTV { get; set; }
        public string POINTSCHARGED { get; set; }
    }
}
