//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETURNEDPAYMENTFEE
    {
        public decimal LEASE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<byte> MAXTIMESRETURNED { get; set; }
        public Nullable<bool> CERTIFIEDCHECK { get; set; }
        public Nullable<bool> MONEYORDER { get; set; }
        public Nullable<bool> CASH { get; set; }
        public Nullable<bool> CREDITCARD { get; set; }
        public Nullable<bool> DIRECTDEPOSIT { get; set; }
        public Nullable<bool> ACH { get; set; }
        public Nullable<bool> PAYPALONLINE { get; set; }
        public Nullable<bool> PERSONALCHECK { get; set; }
    }
}
