//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROICALCULATOR
    {
        public decimal ID { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public System.DateTime LASTUSED { get; set; }
        public string CONTENT { get; set; }
    }
}
