//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATELAW
    {
        public decimal ID { get; set; }
        public Nullable<byte> LEASETYPE { get; set; }
        public Nullable<int> HEADER { get; set; }
        public string STATE { get; set; }
        public string TEXT { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
    }
}
