//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY
    {
        public decimal ID { get; set; }
        public Nullable<decimal> REFERRER { get; set; }
        public Nullable<byte> HOWHEARD { get; set; }
        public string HOWHEARDOTHER { get; set; }
        public Nullable<byte> PREVIOUSLYUSING { get; set; }
        public string PREVIOUSLYUSINGOTHER { get; set; }
        public Nullable<System.DateTime> THEDATE { get; set; }
        public Nullable<short> PROPERTIESOWNED { get; set; }
        public Nullable<decimal> CAMPAIGNID { get; set; }
        public string GENERALWHYCHOSEUS { get; set; }
        public System.DateTime UPDATED { get; set; }
        public Nullable<bool> DISPLAY { get; set; }
        public string WHATTOCHANGE { get; set; }
    }
}
