//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_APPLICANT
    {
        public decimal ID { get; set; }
        public Nullable<decimal> APPLICATIONID { get; set; }
        public Nullable<decimal> TAUSERID { get; set; }
        public Nullable<decimal> TU_APPID { get; set; }
        public string APPLICANTEMAIL { get; set; }
        public string APPLICANTNAME { get; set; }
        public byte EMAILSENT { get; set; }
        public Nullable<byte> EMAILBOUNCESTATUS { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<System.DateTime> RESPONSEDATE { get; set; }
        public Nullable<byte> TUREQUESTSTATUS { get; set; }
        public Nullable<byte> PAIDFORSTATUS { get; set; }
        public Nullable<decimal> ORDERID { get; set; }
        public Nullable<byte> PAIDBY { get; set; }
        public Nullable<decimal> TENANTID { get; set; }
        public Nullable<byte> REQUESTSTATUS { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string SSN { get; set; }
        public Nullable<byte> MARITALSTATUS { get; set; }
        public string DRIVERSLICENSENUM { get; set; }
        public string HOMEPHONENUMBER { get; set; }
        public string CELLPHONENUMBER { get; set; }
        public string WORKPHONENUMBER { get; set; }
        public string WORKPHONEEXT { get; set; }
        public Nullable<byte> RA_Q_SUEDBILLS { get; set; }
        public Nullable<byte> RA_Q_BANKRUPT { get; set; }
        public Nullable<byte> RA_Q_FELONY { get; set; }
        public Nullable<byte> RA_Q_BROKENLEASE { get; set; }
        public Nullable<byte> RA_Q_LOCKEDSHERIF { get; set; }
        public Nullable<byte> RA_Q_COURT { get; set; }
        public Nullable<byte> RA_Q_DAMAGED { get; set; }
        public Nullable<byte> RA_Q_MOVEINAMOUNT { get; set; }
        public Nullable<byte> EMPLOYMENTSTATUS { get; set; }
        public Nullable<decimal> ASSETVALUE { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string LASTNAME { get; set; }
        public Nullable<byte> HASINCOMES { get; set; }
        public Nullable<byte> HASHOMES { get; set; }
        public Nullable<byte> HASOCCUPANTS { get; set; }
        public Nullable<byte> HASPETS { get; set; }
        public Nullable<byte> HASEMPLOYERS { get; set; }
        public Nullable<byte> HASVEHICLES { get; set; }
        public Nullable<byte> HASCREDITCARDS { get; set; }
        public Nullable<byte> HASCARLOANS { get; set; }
        public Nullable<byte> HASOTHERFINANCIALS { get; set; }
        public Nullable<byte> HASBANKACCOUNTS { get; set; }
        public Nullable<byte> HASCONTACTS { get; set; }
        public bool LEGACYSMARTMOVE { get; set; }
        public bool STATUS { get; set; }
        public Nullable<System.DateTime> LASTEDITED { get; set; }
        public Nullable<System.DateTime> REQUESTNOTIFICATION { get; set; }
        public Nullable<System.DateTime> REQUESTREMINDERNOTIFICATION { get; set; }
        public Nullable<System.DateTime> APPINCOMPLETENOTIFICATION { get; set; }
        public Nullable<System.DateTime> LANDLORDINCOMPLETENOTIFICATION { get; set; }
        public string DRIVERSLICENSESTATE { get; set; }
        public Nullable<bool> PRIMARYPHONE { get; set; }
        public Nullable<bool> SECONDARYPHONE { get; set; }
        public string SECONDARYPHONENUMBER { get; set; }
        public string SECONDARYPHONEEXT { get; set; }
    }
}
