//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TENANT
    {
        public decimal ID { get; set; }
        public decimal USERID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string SSN { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public string EIN { get; set; }
    }
}
