//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TENANTS2LEASES
    {
        public decimal LEASE { get; set; }
        public decimal TENANT { get; set; }
        public Nullable<byte> SORTORDER { get; set; }
        public string DOINGBUSINESSAS { get; set; }
        public Nullable<bool> HASDBA { get; set; }
        public Nullable<bool> HASGUARANTORS { get; set; }
    }
}
