//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIRDPARTYMEMBERSREPORT
    {
        public decimal ID { get; set; }
        public Nullable<byte> THIRDPARTY { get; set; }
        public Nullable<System.DateTime> REPORTDATE { get; set; }
        public Nullable<int> PROPERTIES { get; set; }
        public Nullable<int> USERS { get; set; }
    }
}
