//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSUNIONAPPLICANT
    {
        public decimal APPLICATIONID { get; set; }
        public Nullable<decimal> TENANTID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public bool EMAILSENT { get; set; }
        public Nullable<bool> EMAILBOUNCESTATUS { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<System.DateTime> RESPONSEDATE { get; set; }
        public Nullable<bool> REQUESTSTATUS { get; set; }
        public Nullable<bool> PAIDFORSTATUS { get; set; }
        public Nullable<decimal> ORDERID { get; set; }
    }
}
