//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSUNIONAPPLICATION
    {
        public decimal ID { get; set; }
        public Nullable<decimal> PROPERTYID { get; set; }
        public Nullable<decimal> ORGANIZATIONID { get; set; }
        public string PUSHNOTIFICATION { get; set; }
        public Nullable<bool> SENDNOTIFICATION { get; set; }
        public Nullable<bool> APPLICATIONSTATUS { get; set; }
        public Nullable<decimal> ORDERID { get; set; }
        public Nullable<bool> PAIDFORSTATUS { get; set; }
        public Nullable<System.DateTime> SUBMITTEDDATE { get; set; }
        public Nullable<decimal> PRICEPERAPPLICANT { get; set; }
        public Nullable<bool> PUSHNOTIFICATION2 { get; set; }
        public decimal RENTAMOUNT { get; set; }
        public Nullable<System.DateTime> DATEDENIED { get; set; }
        public Nullable<decimal> PROMOCODE { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
