//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUSTPILOTREVIEW
    {
        public decimal REVIEWID { get; set; }
        public string NAME { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public decimal STARS { get; set; }
        public Nullable<System.DateTime> CREATEDTIME { get; set; }
        public string TRUSTPILOTID { get; set; }
    }
}
