//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public decimal ID { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<float> USERACCESS { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> LASTDATE { get; set; }
        public string FIRST { get; set; }
        public string LAST { get; set; }
        public string COMPANY { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public Nullable<System.DateTime> MEMBERSHIPEXP { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public Nullable<byte> ISTRIAL { get; set; }
        public Nullable<bool> AUTORENEW { get; set; }
        public string NAMEONCARD { get; set; }
        public string CCNUM { get; set; }
        public Nullable<bool> CCTYPE { get; set; }
        public Nullable<System.DateTime> CCEXP { get; set; }
        public string CCCODE { get; set; }
        public Nullable<bool> ISVALIDATED { get; set; }
        public Nullable<bool> ISPAID { get; set; }
        public Nullable<short> PROPERTIES { get; set; }
        public Nullable<bool> MAILSTATUS { get; set; }
        public Nullable<int> REFERRERID { get; set; }
        public string REFERRERURL { get; set; }
        public string REFERRERKEYWORDS { get; set; }
        public Nullable<decimal> CAMPAIGNID { get; set; }
        public string BILLFIRST { get; set; }
        public string BILLLAST { get; set; }
        public string BILLCOMPANY { get; set; }
        public string BILLEMAIL { get; set; }
        public string BILLPHONE { get; set; }
        public string BILLADDRESS1 { get; set; }
        public string BILLADDRESS2 { get; set; }
        public string BILLCITY { get; set; }
        public string BILLSTATE { get; set; }
        public string BILLZIP { get; set; }
        public Nullable<decimal> AFFILIATEREFERRER { get; set; }
        public string ADDITIONALSTATES { get; set; }
        public string PRIMARYSTATE { get; set; }
        public string BILLCOUNTRY { get; set; }
        public byte THIRDPARTYINTEGRATION { get; set; }
        public bool HASCREDITCHECKSERVICE { get; set; }
        public System.DateTime CREDITCHECKSERVICECHANGEDATE { get; set; }
        public string ADMINNOTES { get; set; }
        public string COUNTRY { get; set; }
        public string PRIMARYCOUNTRY { get; set; }
        public Nullable<System.DateTime> LOGOUPDATED { get; set; }
        public Nullable<decimal> CLUBREFERRER { get; set; }
        public Nullable<decimal> FACEBOOKID { get; set; }
        public Nullable<decimal> TUORGANIZATIONID { get; set; }
        public Nullable<System.DateTime> TUTERMSOFSERVICEDATE { get; set; }
        public string GOOGLEID { get; set; }
        public Nullable<System.DateTime> PASSWORDCHANGEDDATE { get; set; }
        public string TRANSUNIONPASSWORD { get; set; }
        public Nullable<bool> ISTEMPACCOUNT { get; set; }
        public string PASSWORDHASH { get; set; }
        public Nullable<System.DateTime> FIVEDOLLAROFFEMAILDATE { get; set; }
        public Nullable<System.DateTime> EMAILVERIFIEDDATE { get; set; }
        public string VERIFICATIONCODE { get; set; }
    }
}
