//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZLF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILITYCONTACTINFO
    {
        public decimal ID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public Nullable<byte> CATEGORY { get; set; }
        public Nullable<bool> MODSTATUS { get; set; }
        public string WEBSITE { get; set; }
        public string NOTES { get; set; }
        public string COUNTRY { get; set; }
    }
}
